[workspace]
authors = ["ehsanmok <ehsanmok@users.noreply.github.com>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "uuid"
platforms = ["linux-64", "osx-arm64"]
version = "0.1.1"
preview = ["pixi-build"]

[package]
name = "uuid"
version = "0.1.1"

[package.build]
backend = { name = "pixi-build-rattler-build", version = "*" }

[dependencies]
uuid = { path = "." }
mojo = "==1.0.0b1"

[feature.dev.dependencies]
pre-commit = ">=4.2.0,<5"
mojodoc = { git = "https://github.com/ehsanmok/mojodoc.git", branch = "main" }

[environments]
default = { features = ["dev"], solve-group = "default" }
dev = { features = ["dev"], solve-group = "default" }

[tasks]
# Format
install-pre-commit = "pre-commit install"
format = { cmd = "mojo format uuid tests examples benchmark", depends-on = ["install-pre-commit"] }

# Tests
tests = "mojo -I . tests/test_core.mojo && mojo -I . tests/test_v4.mojo && mojo -I . tests/test_v7.mojo && mojo -I . tests/test_simd_hex.mojo"
test-core = "mojo -I . tests/test_core.mojo"
test-v4 = "mojo -I . tests/test_v4.mojo"
test-v7 = "mojo -I . tests/test_v7.mojo"
test-simd-hex = "mojo -I . tests/test_simd_hex.mojo"

# Examples
example = "mojo -I . examples/example.mojo"

# Benchmark
bench = "mojo -I . benchmark/bench.mojo"

# Docs
docs = "mojodoc ./uuid --open"
docs-build = "mojodoc ./uuid --out-dir target/doc --base-url /uuid/"

